### ISSUE TITLE
Can't ADD or DELETE

### ISSUE THREAD

**Issue by pinkfloydFR** [VincentCinque/MakersVault#8]
Hi,

Trying to deploy in docker environment, can't add or delete "default" file.

Tested write access inside the docker is ok : 

<img width="612" height="213" alt="Image" src="https://github.com/user-attachments/assets/076bba11-8fb6-46d0-bf72-bba39b0e8fbd" />

But in the interface : 

<img width="1898" height="818" alt="Image" src="https://github.com/user-attachments/assets/2e799129-8a76-4471-9b7d-1ccd6be9aa99" />

Here is my docker compose (test is actually local, not using traefik, so you can ignore this part)

```
---
services:
  api:
    image: shotgunwilly555/makersvault-api:latest
    restart: unless-stopped
    container_name: makervault_api
    environment:
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=super-secret
      - AUTH_SECRET=7l0PExxxxnGrmLpF
      - AUTH_TOKEN_TTL=43200
      - FILE_STORAGE=/app/storage
      - DB_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://192.168.0.6:5173
    volumes:
      - ./storage:/app/storage
      - ./db:/app/data
    ports:
      - "9700:8000"
    networks:
      makervault:

  web:
    image: shotgunwilly555/makersvault-web:latest
    container_name: makervault_web
    privileged: false
    environment:
      - VITE_API_URL=http://192.168.0.6:9700
      - TZ=Europe/Paris
    ports:
      - 5173:5173
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.makervault.rule=Host(`makervault.xxxxx.com`)
      - traefik.http.routers.makervault.entrypoints=websecure
      - traefik.http.routers.makervault.service=makervault
      - traefik.http.routers.makervault.tls=true
      - traefik.http.routers.makervault.middlewares=crowdsec-bouncer@docker,my-geoblock@file,authelia_df@docker,sslheader@docker
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.services.makervault.loadbalancer.server.port=5173
    depends_on:
      - api
    networks:
      makervault:
      traefik:

networks:
  makervault:
    name: makervault
    driver_opts:
      com.docker.network.bridge.name: br-makervault
```

Here is a log when trying to add a 3mf : 

```
192.168.0.3:3290 - "POST /upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 211, in upload
    s.commit()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2030, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1311, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1286, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4331, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4466, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4427, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1419, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO asset (id, filename, mime, size, tags_json, title, notes, folder_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('1c49dc7b-7b21-4550-866c-55217fa1a1c4', 'wemos1_3_oled_v5.2.3mf', 'application/octet-stream', 0, '[]', None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

readonly database ?

Thanks !

**Comment by VincentCinque** [comment]
Hey, this release is still in beta. Still doing my own testing v4 is latest stable. I think what is happening is I've added a feature to run the container as non-root user - this seems like a permissions issue between the web api container and the actual web interface. Please let me know if below works - My apologies, all my testing was done on localhost (Docker Desktop) and I pushed latest release last night to test on my Linux server. The readme with update instructions will be released shortly once I work out a few more kinks in documentation today. Hope this helps. If it does not please feel free to reach out on discord _shotgunwilly and I can help you troubleshoot further. 

PUID=1000 # <------
PGID=1000 # <-------
API_IMAGE=shotgunwilly555/makersvault-api:latest
WEB_IMAGE=shotgunwilly555/makersvault-web:latest
FILE_STORAGE=/app/storage
DB_URL=sqlite:///./app.db
CORS_ORIGINS=http://10.0.0.160:5173
VITE_ALLOWED_HOSTS=10.0.0.160
VITE_API_URL=http://10.0.0.160:8230
AUTH_USERNAME=
AUTH_PASSWORD=
AUTH_SECRET=replace-with-random-secret
AUTH_TOKEN_TTL=43200

#----Docker Compose File -----

version: "3.9"
services:
  api:
    image: ${API_IMAGE:-shotgunwilly555/makersvault-api:latest}
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000} # <-------
      - PGID=${PGID:-1000} # <------
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-super-secret}
      - AUTH_SECRET=${AUTH_SECRET:-changeme-secret}
      - AUTH_TOKEN_TTL=${AUTH_TOKEN_TTL:-43200}
      - FILE_STORAGE=/app/storage
      - DB_URL=sqlite:////app/data/app.db
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
    volumes:
      - makersvault_storage:/app/storage
      - makersvault_db:/app/data
    ports:
      - "8230:8000"

  web:
    image: ${WEB_IMAGE:-shotgunwilly555/makersvault-web:latest}
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS:-localhost}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
      - PUID=${PUID:-1000} #<-------
      - PGID=${PGID:-1000} #<-------
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173","--strictPort"]
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  makersvault_storage:
  makersvault_db:

**Comment by pinkfloydFR** [comment]
Hi,

No problem, understood that this project is a new born ^^

Tested with volume, so no mapped folder, still the same issue as db is read only...

<img width="1205" height="94" alt="Image" src="https://github.com/user-attachments/assets/5ba95ae2-a02f-4c98-99b0-bffdc21cf299" />

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database
```


```
services:
  api:
    image: shotgunwilly555/makersvault-api:latest
    restart: unless-stopped
    container_name: makervault_api
    environment:
      - PUID=1000
      - GUID=1000
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=super-secret
      - AUTH_SECRET=7l0PEabkzMxxxxuRYnGrmLpF
      - AUTH_TOKEN_TTL=43200
      - FILE_STORAGE=/app/storage
      - DB_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://192.168.0.6:5173
    volumes:
      - makersvault_storage:/app/storage
      - makersvault_db:/app/data
    ports:
      - "9700:8000"
    networks:
      makervault:

  web:
    image: shotgunwilly555/makersvault-web:latest
    container_name: makervault_web
    privileged: false
    environment:
      - PUID=1000
      - GUID=1000
      - VITE_API_URL=http://192.168.0.6:9700
      - VITE_ALLOWED_HOSTS=localhost
      - TZ=Europe/Paris
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173","--strictPort"]
    ports:
      - 5173:5173
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.makervault.rule=Host(`makervault.xxxxxx.com`)
      - traefik.http.routers.makervault.entrypoints=websecure
      - traefik.http.routers.makervault.service=makervault
      - traefik.http.routers.makervault.tls=true
      - traefik.http.routers.makervault.middlewares=crowdsec-bouncer@docker,my-geoblock@file,authelia_df@docker,sslheader@docker
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.services.makervault.loadbalancer.server.port=5173
    depends_on:
      - api
    networks:
      makervault:
      traefik:

volumes:
  makersvault_storage:
  makersvault_db:

networks:
  makervault:
    name: makervault
    driver_opts:
      com.docker.network.bridge.name: br-makervault
  traefik:
    external: true

```

PUID and GUID 1000 not helping...
